[project]
name = "repl-nix-telebot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "pytelegrambotapi>=4.23.0",
    "python-box>=7.2.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
